name: vite2-vue3-template
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      # 安装依赖
      - run: npm ci

      # 打包
      - run: npm run build

      # 部署
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.PRIVATE_KEY }}
          BRANCH: gh-pages
          FOLDER: dist
          REPOSITORY_NAME: ysz0602/vite2-vue3-template
          TARGET_FOLDER: vite2-vue3-template
        # with:
        #   PERSONAL_TOKEN: ${{secrets.PRIVATE_KEY}}
        #   BRANCH: gh-pages # 存放产物的分支名称
        #   FOLDER: dist # 存放build后产物的目录
        #   BUILD_SCRIPT: npm install && npm run build # 执行的命令